#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
# root@OpenWrt:/# /etc/init.d/telemetry enable

START=21
 
start() {        
        echo start
        /usr/bin/telemetry &
}                 
